### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by victor-iyi** [DotunLonge/Beat-Maker#1]
Bro, the application is awesome! I was thinking you should include a feature to reset the beat you've created so as to start on a clean slate. Then maybe if it's possible to save the beat you just created. 😃

**Comment by dotunlonge** [comment]
Hello Victor, i like the reset idea, i've been pondering on the save
feature as well. Sadly, real work has not given me time to battle it, will
let you know how it goes. Thanks for checking it out tho. :D

**Comment by victor-iyi** [comment]
Yrah bro... Anytime!
